# Generated by Django 3.1.3 on 2020-12-16 04:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_like_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 16, 10, 0, 15, 381569)),
        ),
    ]
