# Generated by Django 3.1.3 on 2020-12-16 13:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20201216_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 16, 18, 37, 26, 946544)),
        ),
    ]
