# Generated by Django 3.1.3 on 2020-12-18 13:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_auto_20201216_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 18, 18, 31, 32, 568694)),
        ),
    ]
