# Generated by Django 3.1.3 on 2020-12-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatechatroom',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
